url: http://localhost:5000
webUrl: http://localhost:3000
databaseUrl: postgresql://voltaserve:voltaserve@localhost:5432/voltaserve
security:
  jwtSigningKey: '3t02Axn$ozfsLnYxEZSAQkmuZnx'
  corsOrigins:
    - http://localhost:3000
s3:
  url: localhost:9000
  accessKey: voltaserve
  secretKey: voltaserve
  region: us-east-1
  secure: false
search:
  url: http://localhost:7700
redis:
  addr: localhost:6379
  password:
  db: 0
smtp:
  host: localhost
  port: 25
  secure: false
  username:
  password:
  senderAddress: no-reply@localhost
  senderName: 'Voltaserve (localhost)'
limits:
  externalCommandTimeoutSec: 60
  fileProcessingMaxSizeMb: 100
  imagePreviewMaxWidth: 512
  imagePreviewMaxHeight: 512
  multipartBodyLengthLimitMb: 1000
