# Copyright 2023 Daniel Sonck, Piotr Łoboda.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the GNU Affero General Public License v3.0 only, included in the file
# licenses/AGPL.txt.

name: Lint voltaserve/idp

on:
  pull_request:
    branches:
      - main
    paths:
      - "idp/**"
      
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Lint using Golanci lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: idp
    permissions:
      contents: read
      pull-requests: read
      checks: write
