name: Build and Push voltaserve/watermark

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "watermark/**"
  pull_request:
    branches:
      - main
    paths:
      - "watermark/**"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./watermark
          push: true
          tags: voltaserve/watermark:latest
          platforms: linux/amd64,linux/arm64
